//
// Created by vepbxer on 4/2/23.
//

#ifndef NYSHPORKA_EXCEPTIONS_H

enum exit_codes {
    WRONG_ARGUMENTS_COUNT = 1,
    CONFIG_FILE_OPENING_ERROR = 3,
    OUTPUT_FILE_OPENING_ERROR = 4,
    ERROR_IN_CONFIG_FILE = 5,
    ERROR_WRITING_TO_OUTPUT_FILE = 6,
    INPUT_DIRECTORY_ACCESS_ERROR = 26,
    NO_ICU_FOUND = 65
};

#define NYSHPORKA_EXCEPTIONS_H

#endif //NYSHPORKA_EXCEPTIONS_H
